app/models.py
from app import db

class Artifact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    set_key = db.Column(db.String(50), nullable=False)
    slot_key = db.Column(db.String(50), nullable=False)
    level = db.Column(db.Integer, nullable=False)
    rarity = db.Column(db.Integer, nullable=False)
    main_stat_key = db.Column(db.String(50), nullable=False)
    location = db.Column(db.String(50), nullable=False)
    lock = db.Column(db.Boolean, default=False)

    roll_value = db.Column(db.Float, nullable=False)

    # Relationship with the Substat model
    substats = db.relationship('Substat', backref='artifact', lazy=True, cascade='all, delete-orphan')

class Substat(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    key = db.Column(db.String(50), nullable=False)
    value = db.Column(db.Float, nullable=False)

    roll_value = db.Column(db.Float, nullable=False)
    
    # Foreign key to relate each substat to an artifact
    artifact_id = db.Column(db.Integer, db.ForeignKey('artifact.id'), nullable=False)

app/__init__.py
""" Application factory """

import os
from flask import Flask

from app.db import db
from app.routes import artifact


def create_app():
    """ Create app, register blueprints and DB """
    app = Flask(__name__, instance_relative_config=True)

    # Set default config
    app.config.from_mapping(
        SECRET_KEY = 'dev',
        SQLALCHEMY_DATABASE_URI = 'sqlite:///site.sqlite',
        SQLALCHEMY_TRACK_MODIFICATIONS = False
    )

    # Set config from instance config, if it exists
    app.config.from_pyfile('config.py', silent=True)

    # Register database
    db.init_app(app)

    # Register modules
    app.register_blueprint(artifact.bp)

    app.add_url_rule('/', endpoint='artifact.welcome')

    return app

app/db/__init__.py
from .sqlite_db import db

app/routes/artifact.py
import json
from flask import Blueprint, render_template, request, redirect, url_for

from app.models import Artifact, Substat, db
from app.utils import format_artifact_substat_text, format_artifact_set_key, calculate_roll_value, calculate_each_roll, min


bp = Blueprint('artifact', __name__, url_prefix='/artifact')

@bp.route('/')
def welcome():
    return render_template('welcome.html')

@bp.route('/view')
def view():
    artifacts = Artifact.query.all()
    return render_template(
        'artifact/view.html', 
        artifacts=artifacts,
        format_artifact_substat_text=format_artifact_substat_text,
        format_artifact_set_key=format_artifact_set_key,
        calculate_each_roll = calculate_each_roll,
        min=min
    )

# @bp.route('/add_artifact', methods=['POST'])
# def add_artifact():
#     set_key = request.form.get('set_key')
#     slot_key = request.form.get('slot_key')
#     rarity = request.form.get('rarity')
#     main_stat_key = request.form.get('main_stat_key')
#     level = request.form.get('level')

#     new_artifact = Artifact(
#         setKey=set_key, 
#         slotKey=slot_key,
#         rarity=rarity,
#         mainStatKey=main_stat_key,
#         level=level
#     )
#     db.session.add(new_artifact)
#     db.session.commit()
#     return redirect(url_for('main.view_artifacts_page'))

@bp.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        if 'json_file' in request.files and request.files['json_file'].filename:
            json_file = request.files['json_file']
            data = json.load(json_file)
        else:
            data = json.loads(request.form['json_data'])
        
        # print(f"Received Data: {data} : {type(data)}")
        for artifact in data.get('artifacts'):
            # print(f"\n{artifact} : {type(artifact)}")

            substats_data = artifact.get('substats', [])
            substats_list = []
            total_roll_value = 0
            for substat in substats_data:
                roll_value =  calculate_roll_value(substat.get('key'), substat.get('value'))
                total_roll_value += roll_value
                new_substat = Substat(
                    key = substat.get('key'),
                    value = substat.get('value'),
                    roll_value = roll_value
                )
                substats_list.append(new_substat)
            
            new_artifact = Artifact(
                set_key = artifact.get('setKey'),
                slot_key = artifact.get('slotKey'),
                level = artifact.get('level'),
                rarity = artifact.get('rarity'),
                main_stat_key = artifact.get('mainStatKey'),
                location = artifact.get('location'),
                lock = artifact.get('lock'),
                roll_value = total_roll_value
            )

            new_artifact.substats = substats_list
            db.session.add(new_artifact)
        
        db.session.commit()
        return redirect(url_for('artifact.view'))
    
    else:
        return render_template('artifact/add.html')

@bp.route('/delete/<int:artifact_id>', methods=['POST'])
def delete(artifact_id):
    artifact_to_delete = Artifact.query.get(artifact_id)
    db.session.delete(artifact_to_delete)
    db.session.commit()
    return redirect(url_for('artifact.view'))

@bp.route('/delete_all', methods=['POST'])
def delete_all():
    Artifact.query.delete()
    Substat.query.delete()
    db.session.commit()
    return redirect(url_for('artifact.view'))

app/templates/add_artifacts.html
{% extends 'base.html' %}

{% block title %}Add Artifacts{% endblock %}

{% block content %}
    <h2>Add Artifact JSON</h2>
    <form method="POST" action="{{ url_for('main.add_artifact_json') }}" enctype="multipart/form-data" onsubmit="return validateForm()">
        <label for="json_file">Upload JSON File:</label>
        <input type="file" id="json_file" name="json_file" accept=".json"><br>

        <label for="json_data">Paste JSON Data:</label>
        <textarea id="json_data" name="json_data" rows="5" cols="40"></textarea><br>

        <button type="submit">Add Artifacts</button>
    </form>{% endblock %}

app/templates/artifact/add.html
{% extends 'base.html' %}

{% block title %}Add Artifacts{% endblock %}

{% block content %}
    <h2>Add Artifact JSON</h2>
    <form method="POST" action="{{ url_for('artifact.add') }}" enctype="multipart/form-data" onsubmit="return validateForm()">
        <label for="json_file">Upload JSON File:</label>
        <input type="file" id="json_file" name="json_file" accept=".json"><br>

        <label for="json_data">Paste JSON Data:</label>
        <textarea id="json_data" name="json_data" rows="5" cols="40"></textarea><br>

        <button type="submit">Add Artifacts</button>
    </form>{% endblock %}

app/templates/artifact/view.html
{% extends 'base.html' %}

{% block title %}View Artifacts{% endblock %}

{% block content %}
    <h2>View Artifacts</h2>
    <form id="delete-all-form" method="POST" action="{{ url_for('artifact.delete_all') }}">
        <button type="submit" onclick="confirmDeleteArtifacts()">Delete All Artifacts</button>
    </form>

    <script>
        function confirmDeleteArtifacts() {
            if (confirm("Are you sure you want to delete all artifacts?")) {
                document.getElementById("delete-all-form").submit();
            }
        }
    </script>
    
    {% if artifacts %}
    <!-- <table border="1">
        <thead>
            <tr>
                <th>ID</th>
                <th>Set</th>
                <th>Slot</th>
                <th>Level</th>
                <th>Rarity</th>
                <th>Main Stat</th>
                <th>Location</th>
                <th>Lock</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for artifact in artifacts %}
                <tr>
                    <td>{{ artifact.id }}</td>
                    <td>{{ artifact.set_key }}</td>
                    <td>{{ artifact.slot_key }}</td>
                    <td>{{ artifact.level }}</td>
                    <td>{{ artifact.rarity }}</td>
                    <td>{{ artifact.main_stat_key }}</td>
                    <td>{{ artifact.location }}</td>
                    <td>{{ artifact.lock}}</td>
                    <td>
                        <form method="POST" action="{{ url_for('artifact.delete', artifact_id=artifact.id) }}">
                            <button type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table> -->
    <br>
 
    {% set artifact_slot_key_labels = {
        "flower": "Flower of Life",
        "plume": "Plume of Death",
        "sands": "Sands of Eon",
        "goblet": "Goblet of Eonothem",
        "circlet": "Circlet of Logos"
    } %}
    <!-- Bootstrap Card Row -->
    {% set artifacts_per_page = 80 %}
    {% set total_pages = (artifacts|length + artifacts_per_page - 1) // artifacts_per_page %}
    {% set current_page = request.args.get('page', 1) %}
    {% set current_page = current_page|int %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5">
        {% for i in range((current_page - 1) * artifacts_per_page, min(current_page * artifacts_per_page, artifacts|length)) %}
        <!-- Bootstrap Card Column -->
        <div class="col mb-4">
            <!-- Bootstrap Card -->
            <div class="card custom-card custom-card-size">
                <div class="card-body">
                    <!-- Top section for artifact info with background image -->
                    <div class="artifact-card-top">
                        <h5 class="card-title custom-card-text">{{ format_artifact_set_key(artifacts[i].set_key) }}</h5>
                        <p class="card-text custom-card-text">{{ artifact_slot_key_labels.get(artifacts[i].slot_key) }}</p>
                        {% for i in range(artifacts[i].rarity) %}
                            <span class="star">&#9733;</span>
                        {% endfor %}
                        <p class="card-text custom-card-text" style="padding-top: 10px;">Main Stat: {{ artifacts[i].main_stat_key }}</p>
                    </div>
                    <!-- Bottom section for substats without background image -->
                    <div class="artifact-card-top-bottom">
                        <!-- Display Substats -->
                        <ul class="list-group">
                            {% for substat in artifacts[i].substats %}
                                <li class="list-group-item custom-card-text" style="display: flex; justify-content: space-between;">
                                    <div style="flex-grow: 1;margin-right: 20px;">{{ format_artifact_substat_text(substat) }}</div>
                                    <!-- <div>{{ calculate_each_roll(substat.roll_value) }}</div> -->
                                    <div>{{ substat.roll_value }}%</div>
                                </li>  
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <!-- End Bootstrap Card -->
        </div>
        <!-- End Bootstrap Card Column -->
        {% endfor %}
        <!-- Pagination links -->
        <nav aria-label="Page navigation">
            <ul class="pagination">
            {% if current_page != 1 %}
                <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ current_page - 1 }}">Previous</a></li>
            {% endif %}
            {% for page in range(1, total_pages + 1) %}
                <li class="page-item {% if page == current_page %}active{% endif %}"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
            {% endfor %}
            {% if current_page != total_pages %}
                <li class="page-item"><a class="page-link" href="?page={{ current_page + 1 }}">Next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ total_pages }}">Last</a></li>
            {% endif %}
            </ul>
        </nav>
    </div>
    <!-- End Bootstrap Card Row -->

    {% else %}
        <p>No artifacts available.</p>
    {% endif %}
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

    <!-- For Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="{{ url_for('static', filename='js/validation.js') }}"></script>
    <title>{% block title %}Welcome{% endblock %}</title>
</head>
<body>
    <header>
        <h1>Artifact Manager</h1>
        <nav>
            <ul>
                <li><a href="{{ url_for('artifact.welcome') }}">Welcome</a></li>
                <li><a href="{{ url_for('artifact.view') }}">View Artifacts</a></li>
                <li><a href="{{ url_for('artifact.add') }}">Add Artifact</a></li>
            </ul>
        </nav>
    </header>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
    <!-- For Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script> -->
</body>
</html>

app/templates/view_artifacts.html
{% extends 'base.html' %}

{% block title %}View Artifacts{% endblock %}

{% block content %}
    <h2>View Artifacts</h2>
    <form id="delete-all-form" method="POST" action="{{ url_for('main.delete_all_artifacts') }}">
        <button type="submit" onclick="confirmDeleteArtifacts()">Delete All Artifacts</button>
    </form>

    <script>
        function confirmDeleteArtifacts() {
            if (confirm("Are you sure you want to delete all artifacts?")) {
                document.getElementById("delete-all-form").submit();
            }
        }
    </script>
    
    {% if artifacts %}
    <!-- <table border="1">
        <thead>
            <tr>
                <th>ID</th>
                <th>Set</th>
                <th>Slot</th>
                <th>Level</th>
                <th>Rarity</th>
                <th>Main Stat</th>
                <th>Location</th>
                <th>Lock</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for artifact in artifacts %}
                <tr>
                    <td>{{ artifact.id }}</td>
                    <td>{{ artifact.set_key }}</td>
                    <td>{{ artifact.slot_key }}</td>
                    <td>{{ artifact.level }}</td>
                    <td>{{ artifact.rarity }}</td>
                    <td>{{ artifact.main_stat_key }}</td>
                    <td>{{ artifact.location }}</td>
                    <td>{{ artifact.lock}}</td>
                    <td>
                        <form method="POST" action="{{ url_for('main.delete_artifact', artifact_id=artifact.id) }}">
                            <button type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table> -->
    <br>
 
    {% set artifact_slot_key_labels = {
        "flower": "Flower of Life",
        "plume": "Plume of Death",
        "sands": "Sands of Eon",
        "goblet": "Goblet of Eonothem",
        "circlet": "Circlet of Logos"
    } %}
    <!-- Bootstrap Card Row -->
    {% set artifacts_per_page = 80 %}
    {% set total_pages = (artifacts|length + artifacts_per_page - 1) // artifacts_per_page %}
    {% set current_page = request.args.get('page', 1) %}
    {% set current_page = current_page|int %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5">
        {% for i in range((current_page - 1) * artifacts_per_page, min(current_page * artifacts_per_page, artifacts|length)) %}
        <!-- Bootstrap Card Column -->
        <div class="col mb-4">
            <!-- Bootstrap Card -->
            <div class="card custom-card custom-card-size">
                <div class="card-body">
                    <!-- Top section for artifact info with background image -->
                    <div class="artifact-card-top">
                        <h5 class="card-title custom-card-text">{{ format_artifact_set_key(artifacts[i].set_key) }}</h5>
                        <p class="card-text custom-card-text">{{ artifact_slot_key_labels.get(artifacts[i].slot_key) }}</p>
                        {% for i in range(artifacts[i].rarity) %}
                            <span class="star">&#9733;</span>
                        {% endfor %}
                        <p class="card-text custom-card-text" style="padding-top: 10px;">Main Stat: {{ artifacts[i].main_stat_key }}</p>
                    </div>
                    <!-- Bottom section for substats without background image -->
                    <div class="artifact-card-top-bottom">
                        <!-- Display Substats -->
                        <ul class="list-group">
                            {% for substat in artifacts[i].substats %}
                                <li class="list-group-item custom-card-text" style="display: flex; justify-content: space-between;">
                                    <div style="flex-grow: 1;margin-right: 20px;">{{ format_artifact_substat_text(substat) }}</div>
                                    <!-- <div>{{ calculate_each_roll(substat.roll_value) }}</div> -->
                                    <div>{{ substat.roll_value }}%</div>
                                </li>  
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <!-- End Bootstrap Card -->
        </div>
        <!-- End Bootstrap Card Column -->
        {% endfor %}
        <!-- Pagination links -->
        <nav aria-label="Page navigation">
            <ul class="pagination">
            {% if current_page != 1 %}
                <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ current_page - 1 }}">Previous</a></li>
            {% endif %}
            {% for page in range(1, total_pages + 1) %}
                <li class="page-item {% if page == current_page %}active{% endif %}"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
            {% endfor %}
            {% if current_page != total_pages %}
                <li class="page-item"><a class="page-link" href="?page={{ current_page + 1 }}">Next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ total_pages }}">Last</a></li>
            {% endif %}
            </ul>
        </nav>
    </div>
    <!-- End Bootstrap Card Row -->

    {% else %}
        <p>No artifacts available.</p>
    {% endif %}
{% endblock %}

app/templates/welcome.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <h2>Welcome to the Artifact Manager!</h2>
    <p>This is the default welcome page.</p>
{% endblock %}